version: "3"

services:
  grafana:
    image: "grafana/grafana:${GRAF_TAG-latest}"
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: grafana-worldmap-panel
    volumes:
      - "${PWD-.}/grafana:/var/lib/grafana"

  influxdb:
    image: "influxdb:${INFL_TAG-latest}"
    ports:
      - "8086:8086"
    volumes:
      - "${PWD-.}/influxdb:/var/lib/influxdb"
